const catalogo = [
  {
    id: 1,
    titulo: "Super Mario 64",
    plataforma: "N64",
    categoria: "Plataformas",
    precioBase: 25,
    estado: "usado-caja-danada",
    stock: 3,
  },
  {
    id: 2,
    titulo: "Final Fantasy VII",
    plataforma: "PS1",
    categoria: "RPG",
    precioBase: 40,
    estado: "usado-como-nuevo",
    stock: 5,
  },
  {
    id: 3,
    titulo: "Sonic the Hedgehog 2",
    plataforma: "MEGA DRIVE",
    categoria: "Plataformas",
    precioBase: 20,
    estado: "solo-cartucho",
    stock: 7,
  },
  {
    id: 4,
    titulo: "Street Fighter II Turbo",
    plataforma: "SNES",
    categoria: "Lucha",
    precioBase: 35,
    estado: "usado-caja-danada",
    stock: 2,
  },
  {
    id: 5,
    titulo: "Tetris",
    plataforma: "GAME BOY",
    categoria: "Puzzle",
    precioBase: 15,
    estado: "solo-cartucho",
    stock: 10,
  },
  {
    id: 6,
    titulo: "Pokémon Rojo",
    plataforma: "GAME BOY",
    categoria: "RPG",
    precioBase: 55,
    estado: "nuevo-precintado",
    stock: 1,
  },
  {
    id: 7,
    titulo: "International Superstar Soccer Deluxe",
    plataforma: "SNES",
    categoria: "Deportes",
    precioBase: 30,
    estado: "usado-como-nuevo",
    stock: 4,
  },
  {
    id: 8,
    titulo: "Tekken 3",
    plataforma: "PS1",
    categoria: "Lucha",
    precioBase: 25,
    estado: "usado-como-nuevo",
    stock: 6,
  },
  {
    id: 9,
    titulo: "Mario Kart 64",
    plataforma: "N64",
    categoria: "Carreras",
    precioBase: 35,
    estado: "nuevo-precintado",
    stock: 3,
  },
  {
    id: 10,
    titulo: "Columns",
    plataforma: "MEGA DRIVE",
    categoria: "Puzzle",
    precioBase: 12,
    estado: "usado-caja-danada",
    stock: 5,
  },
  {
    id: 11,
    titulo: "Super Mario World",
    plataforma: "SNES",
    categoria: "Plataformas",
    precioBase: 30,
    estado: "nuevo-precintado",
    stock: 8,
  },
  {
    id: 12,
    titulo: "NBA Jam",
    plataforma: "MEGA DRIVE",
    categoria: "Deportes",
    precioBase: 18,
    estado: "solo-cartucho",
    stock: 4,
  },
];


function reglasNegocio(idBuscado){
    const juegoBuscado=catalogo.find((producto)=>producto.id===idBuscado);
}
